Update for new tufrepo tool
* remove the vendored tool
* update workflows

diff --git a/.github/workflows/pr-test.yml b/.github/workflows/pr-test.yml
--- a/.github/workflows/pr-test.yml
+++ b/.github/workflows/pr-test.yml
@@ -1,4 +1,4 @@
-name: TUF repository test
+name: TUF repository snapshot test
 
 on:
   pull_request:
@@ -16,21 +16,21 @@ jobs:
 
       - name: install dependencies
         run: |
-          pip install securesystemslib[pynacl]
           pip install git+https://github.com/theupdateframework/tuf.git
-          pip install click
+          pip install git+https://github.com/vmware-labs/repository-editor-for-tuf.git
 
-      - name: Test tufctl for repo snapshot
+      - name: tufrepo snapshot test for PRs
         env:
-          online_keys: ${{ secrets.online_keys }}
+          TUF_REPO_PRIVATE_KEY_38600820f11a5f7d7ff42e6dfc9b03fd60272a3be6f895da2d882cea8bb1e20f: ${{ secrets.TUF_REPO_PRIVATE_KEY_38600820f11a5f7d7ff42e6dfc9b03fd60272a3be6f895da2d882cea8bb1e20f }}
+          TUF_REPO_PRIVATE_KEY_9d78543b508f99a95a3c31fad3cffef0644134f1a028b30501acc12058c7c3e8: ${{ secrets.TUF_REPO_PRIVATE_KEY_9d78543b508f99a95a3c31fad3cffef0644134f1a028b30501acc12058c7c3e8 }}
         run: |
           cd metadata
 
           # return error if 
-          # * status is non-zero and 
-          # * creating a snapshot does not help
-          ../tufctl/tufctl status || {
+          # * verify fails and 
+          # * after snapshot, verify still fails
+          tufrepo verify --root-hash 24d9b03f10ce0fe2e648833de26af60a4a8cd4e65bb396a8200a3194ae8ea76e || {
             echo "repository is not in valid state: running snapshot"
-            ../tufctl/tufctl snapshot
-            ../tufctl/tufctl status
+            tufrepo snapshot
+            tufrepo verify --root-hash 24d9b03f10ce0fe2e648833de26af60a4a8cd4e65bb396a8200a3194ae8ea76e
           }
